package com.sar.web.http;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.Locale;
import java.util.TimeZone;

import org.slf4j.LoggerFactory;

public class Response {
    private static final org.slf4j.Logger logger = LoggerFactory.getLogger(Response.class);

    public ReplyCode code;
    public Headers headers;
    public ArrayList<String> setCookie;

    public String text;
    public File   file;

    private final String serverName;

    // -------------------------------------------------------------------------
    // SSE support
    //
    // For Server-Sent Events the connection must stay open after the HTTP
    // headers are sent.  Two additions make this work without touching
    // AbstractRequestHandler or the controller:
    //
    //   outputStream — the raw socket OutputStream, set by ConnectionThread
    //                  before the controller runs, so EventHandler can write
    //                  directly to the wire.
    //
    //   sseConnection — flag set by EventHandler.handleGet() to tell
    //                   ConnectionThread.run() that it must NOT call
    //                   send_Answer() or enter the keep-alive loop; the SSE
    //                   thread holds the connection open itself.
    // -------------------------------------------------------------------------
    private OutputStream outputStream;
    private boolean      sseConnection = false;

    public Response(String server_name) {
        this.code      = new ReplyCode();
        this.headers   = new Headers();
        this.setCookie = new ArrayList<>();
        this.serverName = server_name;
        this.headers.setHeader("Server", server_name);
    }

    // -- existing setters / getters (unchanged) -------------------------------

    public void setCode(int _code)        { code.setCode(_code); }
    public void setVersion(String v)      { code.setVersion(v); }
    public void setHeader(String n, String v) { headers.setHeader(n, v); }
    public void setFile(File file)        { this.file = file; }
    public void setText(String text)      { this.text = text; }
    public void addCookie(String cookie)  { setCookie.add(cookie); }
    public int  getCode()                 { return code.getCode(); }

    public Enumeration<Object> get_Iterator_parameter_names() {
        return headers.getAllHeaderNames();
    }
    public ArrayList<String> getSetCookies() { return setCookie; }

    // -- SSE additions --------------------------------------------------------

    /**
     * Called by ConnectionThread.run() immediately after obtaining the socket
     * OutputStream, so that EventHandler can access it without needing a
     * reference to the socket itself.
     */
    public void setOutputStream(OutputStream outputStream) {
        this.outputStream = outputStream;
    }

    /**
     * Returns the raw socket OutputStream.
     * Used by EventHandler to write SSE frames directly to the wire.
     */
    public OutputStream getOutputStream() {
        return outputStream;
    }

    /**
     * Marks this response as an SSE connection.
     * When true, ConnectionThread skips send_Answer() and the keep-alive loop.
     */
    public void markAsSseConnection() {
        this.sseConnection = true;
    }

    /**
     * Returns true if EventHandler has claimed this connection for SSE.
     */
    public boolean isSseConnection() {
        return sseConnection;
    }

    // -- rest of original code (unchanged) ------------------------------------

    public void setFileHeaders(File file, String contentType) {
        this.file = file;
        this.file = null;
        logger.debug("Header fields not defined in HTTPAnswer.set_file");
    }

    public void setTextHeaders(String text) {
        this.text = text;
        this.file = null;
        logger.debug("Header fields not defined in HTTPAnswer.set_text");
    }

    public void setError(int codeNumber, String version) {
        setVersion(version);
        setDate();
        code.setCode(codeNumber);
        String errorHtml = generateErrorPage(codeNumber);
        setTextHeaders(errorHtml);
    }

    private String generateErrorPage(int code) {
        return String.format(
            "<html><head><title>Error %d</title></head>" +
            "<body><h1>Error %d - %s</h1>" +
            "<p>Generated by %s</p></body></html>",
            code, code, ReplyCode.codeText(code), serverName);
    }

    void setDate() {
        DateFormat httpformat =
                new SimpleDateFormat("EE, d MMM yyyy HH:mm:ss zz", Locale.UK);
        httpformat.setTimeZone(TimeZone.getTimeZone("GMT"));
        headers.setHeader("Date", httpformat.format(new Date()));
    }

    public void send_Answer(PrintStream TextPrinter) throws IOException {
        if (code.getCodeTxt() == null) {
            code.setCode(ReplyCode.BADREQ);
        }
        logger.info("Sending reply: {} {} {}",
                code.getVersion(), code.getCode(), code.getCodeTxt());
        TextPrinter.print(code.toString() + "\r\n");
        headers.writeHeaders(TextPrinter);
        TextPrinter.print("\r\n");

        if (text != null) {
            TextPrinter.print(text);
        } else if (file != null) {
            writeFile(TextPrinter);
        } else if ((code.getCode() != ReplyCode.NOTMODIFIED)
                && (code.getCode() != ReplyCode.TMPREDIRECT)) {
            logger.error("Internal server error sending answer\n");
        }

        TextPrinter.flush();
    }

    private void writeFile(PrintStream TextPrinter) {
        try (FileInputStream fin = new FileInputStream(file)) {
            byte[] data = new byte[fin.available()];
            fin.read(data);
            logger.info("HTTPAnswer may fail for large files - please modify it");
            TextPrinter.write(data);
        } catch (IOException e) {
            System.out.println("I/O error opening FileInputStream " + e);
        }
    }
}